obj-$(CONFIG_AMD_DIAGNOSTICS_AMEX)	+= amex/
obj-$(CONFIG_AMD_DIAGNOSTICS_BTHB)	+= bthb/
obj-$(CONFIG_AMD_DIAGNOSTICS_TEST)	+= test/
obj-$(CONFIG_AMD_DIAGNOSTICS)	        += smi/
obj-$(CONFIG_AMD_DIAGNOSTICS)	        += common/
